import { describe, it, expect } from 'vitest';
import { generateHtmlReport } from '../lib/export-html';
import type { MergedParagraph, Reviewer, CommentStatus } from '../wasm';

// ─── Helpers ────────────────────────────────────────────────────────

function makeStoreSnapshot(overrides: {
  mergedParagraphs?: MergedParagraph[];
  reviewers?: Reviewer[];
  statuses?: Map<string, CommentStatus>;
} = {}) {
  return {
    mergedParagraphs: overrides.mergedParagraphs ?? [],
    reviewers: overrides.reviewers ?? [],
    statuses: overrides.statuses ?? new Map(),
    manualComments: [],
  };
}

function makeParagraph(overrides: Partial<MergedParagraph> = {}): MergedParagraph {
  return {
    index: 0,
    base_text: 'The quick brown fox jumps over the lazy dog.',
    revised_text: 'The quick brown fox jumps over the lazy dog.',
    paragraph_status: 'Normal',
    paragraph_change_author: null,
    reviewer_versions: [],
    comments: [],
    track_changes: [],
    manual_comments: [],
    has_conflicts: false,
    source_file: null,
    has_new_items: false,
    ...overrides,
  };
}

// ─── Tests ──────────────────────────────────────────────────────────

describe('generateHtmlReport', () => {
  it('generates a valid HTML string', () => {
    const html = generateHtmlReport(makeStoreSnapshot());

    expect(html).toContain('<!DOCTYPE html>');
    expect(html).toContain('<html lang="en">');
    expect(html).toContain('</html>');
    expect(html).toContain('<title>Collate Report');
    expect(html).toContain('Generated by Collate');
  });

  it('contains summary table with correct counts', () => {
    const statuses = new Map<string, CommentStatus>();
    statuses.set('tc-1', { comment_id: 'tc-1', status: 'accepted', note: '' });
    statuses.set('c-1', { comment_id: 'c-1', status: 'rejected', note: '' });
    statuses.set('mc-1', { comment_id: 'mc-1', status: 'deferred', note: '' });

    const para = makeParagraph({
      track_changes: [
        {
          id: 'tc-1',
          change_type: 'Insertion',
          author: 'Alice',
          date: null,
          original_text: '',
          new_text: 'added text',
          context_before: '',
          context_after: '',
        },
        {
          id: 'tc-2',
          change_type: 'Deletion',
          author: 'Bob',
          date: null,
          original_text: 'removed text',
          new_text: '',
          context_before: '',
          context_after: '',
        },
      ],
      comments: [
        {
          id: 'c-1',
          author: 'Alice',
          date: null,
          text: 'Please review',
          anchor_text: 'fox',
          initials: null,
        },
      ],
      manual_comments: [
        {
          id: 'mc-1',
          reviewer_name: 'Bob',
          paragraph_index: 0,
          text: 'Discussed in meeting',
          source: 'conference',
          date: '2025-01-15',
        },
      ],
    });

    const html = generateHtmlReport(
      makeStoreSnapshot({ mergedParagraphs: [para], statuses })
    );

    // Total Items = 4 (2 track changes + 1 comment + 1 manual)
    expect(html).toContain('<th>Total Items</th><td>4</td>');
    // Resolved = 3 (accepted + rejected + deferred — all non-unresolved)
    expect(html).toContain('<th>Resolved</th><td>3</td>');
    // Unresolved = 1 (tc-2 has no status entry)
    expect(html).toContain('<th>Unresolved</th><td>1</td>');
    // Individual counts
    expect(html).toContain('<th>Accepted</th><td>1</td>');
    expect(html).toContain('<th>Rejected</th><td>1</td>');
    expect(html).toContain('<th>Deferred</th><td>1</td>');
  });

  it('contains paragraph sections', () => {
    const para = makeParagraph({
      index: 2,
      base_text: 'Introduction to the report.',
      track_changes: [
        {
          id: 'tc-x',
          change_type: 'Insertion',
          author: 'Eve',
          date: null,
          original_text: '',
          new_text: 'new clause',
          context_before: '',
          context_after: '',
        },
      ],
    });

    const html = generateHtmlReport(
      makeStoreSnapshot({ mergedParagraphs: [para] })
    );

    // Paragraph number is index + 1
    expect(html).toContain('¶ 3');
    expect(html).toContain('Introduction to the report.');
    expect(html).toContain('Track Changes');
    expect(html).toContain('Eve');
    expect(html).toContain('new clause');
  });

  it('escapes HTML special characters', () => {
    const para = makeParagraph({
      base_text: 'Use <script>alert("xss")</script> & more',
      comments: [
        {
          id: 'c-esc',
          author: 'O\'Brien & <Co>',
          date: null,
          text: 'Check "quotes" & <tags>',
          anchor_text: '<b>bold</b>',
          initials: null,
        },
      ],
    });

    const html = generateHtmlReport(
      makeStoreSnapshot({ mergedParagraphs: [para] })
    );

    // Angle brackets and ampersands must be escaped
    expect(html).toContain('&lt;script&gt;');
    expect(html).toContain('&amp; more');
    expect(html).toContain('O&#x27;Brien &amp; &lt;Co&gt;'.replace(/&#x27;/g, "'"));
    // The esc function uses &amp; &lt; &gt; &quot;
    expect(html).toContain('&lt;Co&gt;');
    expect(html).toContain('&amp; &lt;tags&gt;');
    expect(html).toContain('&lt;b&gt;bold&lt;/b&gt;');
    expect(html).not.toContain('<script>');
  });

  it('renders status badges correctly', () => {
    const statuses = new Map<string, CommentStatus>();
    statuses.set('tc-unres', { comment_id: 'tc-unres', status: 'unresolved', note: '' });
    statuses.set('tc-accept', { comment_id: 'tc-accept', status: 'accepted', note: '' });
    statuses.set('tc-reject', { comment_id: 'tc-reject', status: 'rejected', note: '' });
    statuses.set('tc-defer', { comment_id: 'tc-defer', status: 'deferred', note: '' });

    const para = makeParagraph({
      track_changes: [
        { id: 'tc-unres', change_type: 'Insertion', author: 'A', date: null, original_text: '', new_text: 'a', context_before: '', context_after: '' },
        { id: 'tc-accept', change_type: 'Insertion', author: 'B', date: null, original_text: '', new_text: 'b', context_before: '', context_after: '' },
        { id: 'tc-reject', change_type: 'Deletion', author: 'C', date: null, original_text: 'c', new_text: '', context_before: '', context_after: '' },
        { id: 'tc-defer', change_type: 'Insertion', author: 'D', date: null, original_text: '', new_text: 'd', context_before: '', context_after: '' },
      ],
    });

    const html = generateHtmlReport(
      makeStoreSnapshot({ mergedParagraphs: [para], statuses })
    );

    // Status badge text
    expect(html).toContain('>unresolved</span>');
    expect(html).toContain('>accepted</span>');
    expect(html).toContain('>rejected</span>');
    expect(html).toContain('>deferred</span>');

    // Badge colours
    expect(html).toContain('background:#d1fae5;color:#065f46'); // accepted
    expect(html).toContain('background:#fee2e2;color:#991b1b'); // rejected
    expect(html).toContain('background:#fef3c7;color:#92400e'); // deferred
    expect(html).toContain('background:#f3f4f6;color:#4b5563'); // unresolved
  });

  it('includes reviewer table when reviewers are present', () => {
    const reviewers: Reviewer[] = [
      { name: 'Alice', file_name: 'doc1.docx', comment_count: 3, change_count: 5, colour: '#EF4444' },
      { name: 'Bob', file_name: 'doc2.docx', comment_count: 1, change_count: 2, colour: '#3B82F6' },
    ];

    const html = generateHtmlReport(
      makeStoreSnapshot({ reviewers })
    );

    expect(html).toContain('Reviewers');
    expect(html).toContain('Alice');
    expect(html).toContain('Bob');
    expect(html).toContain('<td>3</td>');
    expect(html).toContain('<td>5</td>');
  });

  it('omits reviewer table when no reviewers', () => {
    const html = generateHtmlReport(makeStoreSnapshot());
    expect(html).not.toContain('Reviewers');
  });

  it('renders deletion and insertion diff styling', () => {
    const para = makeParagraph({
      track_changes: [
        { id: 'tc-ins', change_type: 'Insertion', author: 'A', date: null, original_text: '', new_text: 'inserted text', context_before: '', context_after: '' },
        { id: 'tc-del', change_type: 'Deletion', author: 'B', date: null, original_text: 'deleted text', new_text: '', context_before: '', context_after: '' },
      ],
    });

    const html = generateHtmlReport(
      makeStoreSnapshot({ mergedParagraphs: [para] })
    );

    expect(html).toContain('<ins');
    expect(html).toContain('inserted text</ins>');
    expect(html).toContain('<del');
    expect(html).toContain('deleted text</del>');
  });

  // ── Wholesale paragraph tests ──────────────────────────────────

  it('renders wholly inserted paragraph with NEW PARAGRAPH badge', () => {
    const para = makeParagraph({
      index: 5,
      base_text: '',
      revised_text: 'This is an entirely new paragraph added by counsel.',
      paragraph_status: 'WhollyInserted',
      paragraph_change_author: 'Senior Counsel',
    });

    const html = generateHtmlReport(
      makeStoreSnapshot({ mergedParagraphs: [para] })
    );

    expect(html).toContain('¶ 6');
    expect(html).toContain('NEW PARAGRAPH');
    expect(html).toContain('This is an entirely new paragraph added by counsel.');
    expect(html).toContain('Added by Senior Counsel');
    // Should have green styling
    expect(html).toContain('#f0fdf4'); // green background
    expect(html).toContain('#bbf7d0'); // green border
    expect(html).toContain('<ins');
    // Left border should be green
    expect(html).toContain('#10b981');
  });

  it('renders wholly deleted paragraph with DELETED PARAGRAPH badge', () => {
    const para = makeParagraph({
      index: 3,
      base_text: 'This paragraph was removed entirely by the partner.',
      revised_text: '',
      paragraph_status: 'WhollyDeleted',
      paragraph_change_author: 'Partner',
    });

    const html = generateHtmlReport(
      makeStoreSnapshot({ mergedParagraphs: [para] })
    );

    expect(html).toContain('¶ 4');
    expect(html).toContain('DELETED PARAGRAPH');
    expect(html).toContain('This paragraph was removed entirely by the partner.');
    expect(html).toContain('Deleted by Partner');
    // Should have red styling
    expect(html).toContain('#fef2f2'); // red background
    expect(html).toContain('#fca5a5'); // red border
    expect(html).toContain('<del');
    // Left border should be red
    expect(html).toContain('#ef4444');
  });

  it('includes wholesale paragraphs even without track_changes/comments', () => {
    // Wholesale paragraphs have no inline track_changes or comments
    // but should still appear in the report
    const normalPara = makeParagraph({
      index: 0,
      base_text: 'Normal paragraph.',
      // No track changes, no comments — should be filtered out
    });
    const insertedPara = makeParagraph({
      index: 1,
      base_text: '',
      revised_text: 'New section added.',
      paragraph_status: 'WhollyInserted',
      paragraph_change_author: 'Alice',
    });
    const deletedPara = makeParagraph({
      index: 2,
      base_text: 'Old section removed.',
      revised_text: '',
      paragraph_status: 'WhollyDeleted',
      paragraph_change_author: 'Bob',
    });

    const html = generateHtmlReport(
      makeStoreSnapshot({ mergedParagraphs: [normalPara, insertedPara, deletedPara] })
    );

    // Normal paragraph with no items should not appear
    expect(html).not.toContain('¶ 1');
    // But wholesale paragraphs should appear
    expect(html).toContain('¶ 2');
    expect(html).toContain('New section added.');
    expect(html).toContain('¶ 3');
    expect(html).toContain('Old section removed.');
  });

  it('wholesale paragraph with no author still renders', () => {
    const para = makeParagraph({
      index: 0,
      base_text: '',
      revised_text: 'Inserted without author attribution.',
      paragraph_status: 'WhollyInserted',
      paragraph_change_author: null,
    });

    const html = generateHtmlReport(
      makeStoreSnapshot({ mergedParagraphs: [para] })
    );

    expect(html).toContain('NEW PARAGRAPH');
    expect(html).toContain('Inserted without author attribution.');
    // Should not contain "Added by" since author is null
    expect(html).not.toContain('Added by');
  });

  it('normal paragraph still renders base_text not wholesale styling', () => {
    const para = makeParagraph({
      index: 0,
      base_text: 'Some regular text.',
      revised_text: 'Some regular text with edits.',
      paragraph_status: 'Normal',
      track_changes: [
        { id: 'tc-1', change_type: 'Insertion', author: 'A', date: null, original_text: '', new_text: 'with edits.', context_before: '', context_after: '' },
      ],
    });

    const html = generateHtmlReport(
      makeStoreSnapshot({ mergedParagraphs: [para] })
    );

    // Should show normal base text, not wholesale badges
    expect(html).toContain('Some regular text.');
    expect(html).not.toContain('NEW PARAGRAPH');
    expect(html).not.toContain('DELETED PARAGRAPH');
    // Border should be default grey
    expect(html).toContain('#d1d5db');
  });
});
